const Team = require('../models/team.model')
const Player = require('../models/player.model')

const DataCreation = (uuid) => {
  return Promise.all([teamsPlayersCreation(uuid)])
}

const teamsPlayersCreation = async (uuid) => {
  await Team.create({
    name: 'Warriors',
    logo: 'https://fr.global.nba.com/media/img/teams/00/logos/GSW_logo.svg',
    UserUuid: uuid,
    salaryCapLeft: 0
  })
  await Team.create({
    name: 'Lakers',
    logo: 'https://fr.global.nba.com/media/img/teams/00/logos/LAL_logo.svg',
    UserUuid: uuid,
    salaryCapLeft: 0
  }),
    await Team.create({
      name: 'Heat',
      logo: 'https://fr.global.nba.com/media/img/teams/00/logos/MIA_logo.svg',
      UserUuid: uuid,
      salaryCapLeft: 0
    }),
    await Team.create({
      name: 'Celtics',
      logo: 'https://fr.global.nba.com/media/img/teams/00/logos/BOS_logo.svg',
      UserUuid: uuid,
      salaryCapLeft: 0
    }),
    await Team.create({
      name: 'Rockets',
      logo: 'https://fr.global.nba.com/media/img/teams/00/logos/HOU_logo.svg',
      UserUuid: uuid,
      salaryCapLeft: 0
    })
  await Team.create({
    name: 'Mavs',
    logo: 'https://fr.global.nba.com/media/img/teams/00/logos/DAL_logo.svg',
    UserUuid: uuid,
    salaryCapLeft: 0
  })
  const lakers = await Team.findOne({
    where: {
      name: 'Lakers',
      UserUuid: uuid
    }
  })
  await Player.create({
    firstName: 'Lebron',
    lastName: 'James',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1966.png&w=350&h=254',
    TeamUuid: lakers.dataValues.uuid,
    UserUuid: uuid,
    value: 98,
    ptsBeg: 17,
    salary: 37000000,
    contractLeft: 2,
    contractYear1: 37000000,
    contractYear2: 37000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 35,
    rebBeg: 5,
    pasBeg: 5,
    ptsMin: 17,
    ptsMax: 37,
    rebMin: 4,
    rebMax: 10,
    pasMin: 5,
    blkMin: 0,
    blkMax: 2,
    stlMin: 0,
    stlMax: 2,
    valueAdjust: 0,
    potential: 85,
    pasMax: 13
  })
  await Player.create({
    firstName: 'Anthony',
    lastName: 'Davis',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6583.png&w=350&h=254',
    TeamUuid: lakers.dataValues.uuid,
    UserUuid: uuid,
    value: 95,
    salary: 27000000,
    contractLeft: 1,
    contractYear1: 27000000,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 27,
    rebBeg: 5,
    pasBeg: 0,
    ptsBeg: 16,
    ptsMin: 16,
    ptsMax: 36,
    rebMin: 5,
    rebMax: 13,
    pasMin: 0,
    blkMin: 1,
    blkMax: 3,
    stlMin: 0.5,
    stlMax: 2.5,
    pasMax: 6,
    valueAdjust: -6,
    potential: 95
  })

  await Player.create({
    firstName: 'Montrezl',
    lastName: 'Harrell',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2991055.png&w=350&h=254',
    TeamUuid: lakers.dataValues.uuid,
    UserUuid: uuid,
    value: 82,
    ptsMin: 8,
    ptsBeg: 8,
    salary: 8000000,
    contractLeft: 2,
    contractYear1: 8000000,
    contractYear2: 8000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 26,
    rebBeg: 3,
    pasBeg: 0,
    ptsMax: 28,
    rebMin: 3,
    rebMax: 11,
    pasMin: 0,
    blkMin: 0,
    blkMax: 2,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 23,
    potential: 85,
    pasMax: 2
  })

  await Player.create({
    firstName: 'Dennis',
    lastName: 'Schroder',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3032979.png&w=350&h=254',
    TeamUuid: lakers.dataValues.uuid,
    UserUuid: uuid,
    value: 80,
    ptsMin: 5,
    ptsBeg: 5,
    salary: 8000000,
    contractLeft: 2,
    contractYear1: 8000000,
    contractYear2: 8000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 27,
    rebBeg: 2,
    pasBeg: 2,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'Kentavious',
    lastName: 'Caldwell-pope',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2581018.png&w=350&h=254',
    TeamUuid: lakers.dataValues.uuid,
    UserUuid: uuid,
    value: 76,
    ptsMin: 4,
    ptsBeg: 4,
    salary: 8000000,
    contractLeft: 2,
    contractYear1: 8000000,
    contractYear2: 8000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 27,
    rebBeg: 0,
    pasBeg: 0,
    ptsMax: 14,
    rebMin: 0,
    rebMax: 4,
    pasMin: 0,
    blkMin: 0.1,
    blkMax: 0.3,
    stlMin: 0,
    stlMax: 2,
    valueAdjust: 39.2,
    potential: 78,
    pasMax: 4
  })

  const warrios = await Team.findOne({
    where: {
      name: 'Warriors',
      UserUuid: uuid
    }
  })
  await Player.create({
    firstName: 'Stephen',
    lastName: 'Curry',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3975.png&w=350&h=254',
    TeamUuid: warrios.dataValues.uuid,
    UserUuid: uuid,
    value: 96,
    ptsBeg: 18,
    salary: 40000000,
    contractLeft: 2,
    contractYear1: 40000000,
    contractYear2: 40000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 32,
    rebBeg: 1,
    pasBeg: 3,
    ptsMin: 18,
    ptsMax: 38,
    rebMin: 1,
    rebMax: 9,
    pasMin: 3,
    blkMin: 0,
    blkMax: 0.8,
    stlMin: 0.5,
    stlMax: 2.5,
    valueAdjust: 10.4,
    potential: 97,
    pasMax: 9
  })
  await Player.create({
    firstName: 'Klay',
    lastName: 'Thompson',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6475.png&w=350&h=254',
    TeamUuid: warrios.dataValues.uuid,
    UserUuid: uuid,
    value: 90,
    ptsMin: 12,
    ptsBeg: 12,
    salary: 32000000,
    contractLeft: 2,
    contractYear1: 32000000,
    contractYear2: 32000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 30,
    rebBeg: 0,
    pasBeg: 0,
    ptsMax: 32,
    rebMin: 0,
    rebMax: 8,
    pasMin: 0,
    blkMin: 0,
    blkMax: 2,
    stlMin: 0.5,
    stlMax: 2.5,
    valueAdjust: 17,
    potential: 93,
    pasMax: 6
  })
  await Player.create({
    firstName: 'Andrew',
    lastName: 'Wiggins',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3059319.png&w=350&h=254',
    TeamUuid: warrios.dataValues.uuid,
    UserUuid: uuid,
    value: 82,
    ptsMin: 11,
    ptsBeg: 11,
    salary: 27000000,
    contractLeft: 2,
    contractYear1: 27000000,
    contractYear2: 27000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 25,
    rebBeg: 1,
    pasBeg: 1,
    ptsMax: 31,
    rebMin: 1,
    rebMax: 9,
    pasMin: 1,
    blkMin: 0,
    blkMax: 2,
    stlMin: 0,
    stlMax: 1.6,
    valueAdjust: 15.7,
    potential: 85,
    pasMax: 6
  })
  await Player.create({
    firstName: 'Draymond',
    lastName: 'Green',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6589.png&w=350&h=254',
    TeamUuid: warrios.dataValues.uuid,
    UserUuid: uuid,
    value: 83,
    ptsMin: 5,
    ptsBeg: 5,
    salary: 18000000,
    contractLeft: 2,
    contractYear1: 18000000,
    contractYear2: 18000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 30,
    rebBeg: 2,
    pasBeg: 3,
    ptsMax: 11,
    rebMin: 2,
    rebMax: 10,
    pasMin: 3,
    blkMin: 0,
    blkMax: 2,
    stlMin: 0.4,
    stlMax: 2.4,
    valueAdjust: 10.4,
    potential: 87,
    pasMax: 9
  })
  await Player.create({
    firstName: 'Kelly',
    lastName: 'Oubre Jr.',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3133603.png&w=350&h=254',
    TeamUuid: warrios.dataValues.uuid,
    UserUuid: uuid,
    value: 81,
    ptsMin: 8,
    ptsBeg: 8,
    salary: 18000000,
    contractLeft: 2,
    contractYear1: 18000000,
    contractYear2: 18000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 24,
    rebBeg: 2,
    pasBeg: 0,
    ptsMax: 28,
    rebMin: 2,
    rebMax: 10,
    pasMin: 0,
    blkMin: 0,
    blkMax: 1.5,
    stlMin: 0.3,
    stlMax: 2.3,
    valueAdjust: 17.5,
    potential: 86,
    pasMax: 2
  })

  const rockets = await Team.findOne({
    where: {
      name: 'Rockets',
      UserUuid: uuid
    }
  })
  await Player.create({
    firstName: 'P.J.',
    lastName: 'Tucker',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3033.png&w=350&h=254',
    TeamUuid: rockets.dataValues.uuid,
    UserUuid: uuid,
    value: 76,
    ptsBeg: 2,
    salary: 8000000,
    contractLeft: 1,
    contractYear1: 8000000,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 35,
    rebBeg: 2,
    pasBeg: 0,
    ptsMin: 2,
    ptsMax: 12,
    rebMin: 2,
    rebMax: 10,
    pasMin: 0,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0.1,
    stlMax: 2.1,
    valueAdjust: 26.6,
    potential: 85,
    pasMax: 3
  })
  await Player.create({
    firstName: 'John',
    lastName: 'Wall',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4237.png&w=350&h=254',
    TeamUuid: rockets.dataValues.uuid,
    UserUuid: uuid,
    value: 83,
    ptsBeg: 10,
    salary: 8000000,
    contractLeft: 1,
    contractYear1: 8000000,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 30,
    rebBeg: 0,
    pasBeg: 6,
    ptsMin: 10,
    ptsMax: 30,
    rebMin: 0,
    rebMax: 6,
    pasMin: 6,
    blkMin: 0,
    blkMax: 1.8,
    stlMin: 0.5,
    stlMax: 2.5,
    valueAdjust: -2.1,
    potential: 90,
    pasMax: 12
  })
  await Player.create({
    firstName: 'Christian',
    lastName: 'Wood',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3058254.png&w=350&h=254',
    TeamUuid: rockets.dataValues.uuid,
    UserUuid: uuid,
    value: 80,
    ptsBeg: 5,
    salary: 8000000,
    contractLeft: 1,
    contractYear1: 8000000,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 25,
    rebBeg: 2,
    pasBeg: 0,
    ptsMin: 5,
    ptsMax: 21,
    rebMin: 2,
    rebMax: 10,
    pasMin: 0,
    blkMin: 0,
    blkMax: 1.8,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 30.9,
    potential: 85,
    pasMax: 2
  })
  // await Player.create({
  //   firstName: 'Robert',
  //   lastName: 'Covington',
  //   photo:
  //     'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2490620.png&w=350&h=254',
  //   TeamUuid: rockets.dataValues.uuid,
  //   UserUuid: uuid,
  //   value: 45.5,
  //   ptsBeg: 5,
  //   salary: 11000000,
  //   contractLeft: 2,
  //   contractYear1: 11000000,
  //   contractYear2: 11000000,
  //   contractYear3: 0,
  //   contractYear4: 0,
  //   age: 28,
  //   rebBeg: 2,
  //   pasBeg: 2,
  //   ptsMin: 5,
  //   ptsMax: 15,
  //   rebMin: 2,
  //   rebMax: 6,
  //   pasMin: 2,
  //   blkMin: 0,
  //   blkMax: 1,
  //   stlMin: 0,
  //   stlMax: 1,
  //   valueAdjust: 34.5,
  //   potential: 85,
  //   pasMax: 6
  // })
  await Player.create({
    firstName: 'Eric',
    lastName: 'Gordon',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3431.png&w=350&h=254',
    TeamUuid: rockets.dataValues.uuid,
    UserUuid: uuid,
    value: 78,
    ptsBeg: 8,
    salary: 14000000,
    contractLeft: 2,
    contractYear1: 14000000,
    contractYear2: 14000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 31,
    rebBeg: 0,
    pasBeg: 0,
    ptsMin: 8,
    ptsMax: 20,
    rebMin: 0,
    rebMax: 4,
    pasMin: 0,
    blkMin: 0,
    blkMax: 0.8,
    stlMin: 0,
    stlMax: 1.2,
    valueAdjust: 43,
    potential: 85,
    pasMax: 2
  })
  await Player.create({
    firstName: 'James',
    lastName: 'Harden',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3992.png&w=350&h=254',
    TeamUuid: rockets.dataValues.uuid,
    UserUuid: uuid,
    value: 95,
    ptsBeg: 24,
    salary: 38000000,
    contractLeft: 2,
    contractYear1: 38000000,
    contractYear2: 38000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 31,
    rebBeg: 2,
    pasBeg: 4,
    ptsMin: 24,
    ptsMax: 44,
    rebMin: 2,
    rebMax: 10,
    pasMin: 4,
    blkMin: 0,
    blkMax: 1.8,
    stlMin: 0.8,
    stlMax: 2.8,
    valueAdjust: -11.3,
    potential: 96,
    pasMax: 10
  })
  // await Player.create({
  //   firstName: 'Russell',
  //   lastName: 'Westbrook',
  //   photo:
  //     'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3468.png&w=350&h=254',
  //   TeamUuid: rockets.dataValues.uuid,
  //   UserUuid: uuid,
  //   value: 45.5,
  //   ptsBeg: 5,
  //   salary: 38000000,
  //   contractLeft: 2,
  //   contractYear1: 38000000,
  //   contractYear2: 38000000,
  //   contractYear3: 0,
  //   contractYear4: 0,
  //   age: 28,
  //   rebBeg: 2,
  //   pasBeg: 2,
  //   ptsMin: 5,
  //   ptsMax: 15,
  //   rebMin: 2,
  //   rebMax: 6,
  //   pasMin: 2,
  //   blkMin: 0,
  //   blkMax: 1,
  //   stlMin: 0,
  //   stlMax: 1,
  //   valueAdjust: 34.5,
  //   potential: 85,
  //   pasMax: 6
  // })
  const mavs = await Team.findOne({
    where: {
      name: 'Mavs',
      UserUuid: uuid
    }
  })
  await Player.create({
    firstName: 'Luka',
    lastName: 'Doncic',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3945274.png&w=350&h=254',
    TeamUuid: mavs.dataValues.uuid,
    UserUuid: uuid,
    value: 94,
    ptsBeg: 19,
    salary: 7000000,
    contractLeft: 1,
    contractYear1: 7000000,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 21,
    rebBeg: 5,
    pasBeg: 6,
    ptsMin: 19,
    ptsMax: 39,
    rebMin: 5,
    rebMax: 13,
    pasMin: 6,
    blkMin: 0,
    blkMax: 0.4,
    stlMin: 0,
    stlMax: 2,
    valueAdjust: -4.8,
    potential: 98,
    pasMax: 12
  })
  await Player.create({
    firstName: 'Kristaps',
    lastName: 'Porzingis',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3102531.png&w=350&h=254',
    TeamUuid: mavs.dataValues.uuid,
    UserUuid: uuid,
    value: 87,
    ptsBeg: 10,
    salary: 27000000,
    contractLeft: 2,
    contractYear1: 27000000,
    contractYear2: 27000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 25,
    rebBeg: 5,
    pasBeg: 0,
    ptsMin: 10,
    ptsMax: 30,
    rebMin: 5,
    rebMax: 13,
    pasMin: 0,
    blkMin: 1,
    blkMax: 3,
    stlMin: 0,
    stlMax: 1.4,
    valueAdjust: 6.2,
    potential: 88,
    pasMax: 4
  })
  await Player.create({
    firstName: 'Tim',
    lastName: 'Hardaway Jr.',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2528210.png&w=350&h=254',
    TeamUuid: mavs.dataValues.uuid,
    UserUuid: uuid,
    value: 78,
    ptsBeg: 10,
    salary: 20000000,
    contractLeft: 2,
    contractYear1: 20000000,
    contractYear2: 20000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 28,
    rebBeg: 1,
    pasBeg: 1,
    ptsMin: 10,
    ptsMax: 22,
    rebMin: 1,
    rebMax: 5,
    pasMin: 1,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 36.8,
    potential: 80,
    pasMax: 3
  })
  // await Player.create({
  //   firstName: 'Seth',
  //   lastName: 'Curry',
  //   photo:
  //     'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2326307.png&w=350&h=254',
  //   TeamUuid: mavs.dataValues.uuid,
  //   UserUuid: uuid,
  //   value: 45.5,
  //   ptsBeg: 5,
  //   salary: 7000000,
  //   contractLeft: 2,
  //   contractYear1: 7000000,
  //   contractYear2: 7000000,
  //   contractYear3: 0,
  //   contractYear4: 0,
  //   age: 28,
  //   rebBeg: 2,
  //   pasBeg: 2,
  //   ptsMin: 5,
  //   ptsMax: 15,
  //   rebMin: 2,
  //   rebMax: 6,
  //   pasMin: 2,
  //   blkMin: 0,
  //   blkMax: 1,
  //   stlMin: 0,
  //   stlMax: 1,
  //   valueAdjust: 34.5,
  //   potential: 85,
  //   pasMax: 6
  // })
  await Player.create({
    firstName: 'Josh',
    lastName: 'Richardson',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2581190.png&w=350&h=254',
    TeamUuid: mavs.dataValues.uuid,
    UserUuid: uuid,
    value: 80,
    ptsBeg: 6,
    salary: 10000000,
    contractLeft: 2,
    contractYear1: 10000000,
    contractYear2: 10000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 27,
    rebBeg: 1,
    pasBeg: 0,
    ptsMin: 6,
    ptsMax: 20,
    rebMin: 1,
    rebMax: 5,
    pasMin: 0,
    blkMin: 0,
    blkMax: 1.4,
    stlMin: 0,
    stlMax: 1.8,
    valueAdjust: 30.1,
    potential: 82,
    pasMax: 6
  })

  await Player.create({
    firstName: 'Dwight',
    lastName: 'Powell',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2531367.png&w=350&h=254',
    TeamUuid: mavs.dataValues.uuid,
    UserUuid: uuid,
    value: 76,
    ptsBeg: 4,
    salary: 10000000,
    contractLeft: 2,
    contractYear1: 10000000,
    contractYear2: 10000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 29,
    rebBeg: 2,
    pasBeg: 0,
    ptsMin: 4,
    ptsMax: 14,
    rebMin: 2,
    rebMax: 10,
    pasMin: 0,
    blkMin: 0,
    blkMax: 1.2,
    stlMin: 0,
    stlMax: 1.8,
    valueAdjust: 26.5,
    potential: 78,
    pasMax: 3
  })
  const celtics = await Team.findOne({
    where: {
      name: 'Celtics',
      UserUuid: uuid
    }
  })
  await Player.create({
    firstName: 'Jayson',
    lastName: 'Tatum',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065648.png&w=350&h=254',
    TeamUuid: celtics.dataValues.uuid,
    UserUuid: uuid,
    value: 90,
    ptsBeg: 13,
    salary: 7000000,
    contractLeft: 1,
    contractYear1: 7000000,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 22,
    rebBeg: 3,
    pasBeg: 0,
    ptsMin: 13,
    ptsMax: 33,
    rebMin: 3,
    rebMax: 11,
    pasMin: 0,
    blkMin: 0,
    blkMax: 2,
    stlMin: 0.4,
    stlMax: 2.4,
    valueAdjust: 8.4,
    potential: 93,
    pasMax: 6
  })
  await Player.create({
    firstName: 'Kemba',
    lastName: 'Walker',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6479.png&w=350&h=254',
    TeamUuid: celtics.dataValues.uuid,
    UserUuid: uuid,
    value: 86,
    ptsBeg: 10,
    salary: 32000000,
    contractLeft: 2,
    contractYear1: 32000000,
    contractYear2: 32000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 30,
    rebBeg: 0,
    pasBeg: 2,
    ptsMin: 10,
    ptsMax: 30,
    rebMin: 0,
    rebMax: 8,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 2,
    valueAdjust: 20.5,
    potential: 90,
    pasMax: 8
  })
  await Player.create({
    firstName: 'Marcus',
    lastName: 'Smart',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2990992.png&w=350&h=254',
    TeamUuid: celtics.dataValues.uuid,
    UserUuid: uuid,
    value: 80,
    ptsBeg: 6,
    salary: 12000000,
    contractLeft: 2,
    contractYear1: 12000000,
    contractYear2: 12000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 26,
    rebBeg: 0,
    pasBeg: 2,
    ptsMin: 6,
    ptsMax: 20,
    rebMin: 0,
    rebMax: 8,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0.7,
    stlMax: 2.7,
    valueAdjust: 11.7,
    potential: 85,
    pasMax: 8
  })
  await Player.create({
    firstName: 'Jaylen',
    lastName: 'Brown',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3917376.png&w=350&h=254',
    TeamUuid: celtics.dataValues.uuid,
    UserUuid: uuid,
    value: 86,
    ptsBeg: 10,
    salary: 6000000,
    contractLeft: 2,
    contractYear1: 6000000,
    contractYear2: 6000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 24,
    rebBeg: 2,
    pasBeg: 1,
    ptsMin: 10,
    ptsMax: 30,
    rebMin: 2,
    rebMax: 10,
    pasMin: 1,
    blkMin: 0,
    blkMax: 0.8,
    stlMin: 0.1,
    stlMax: 2.1,
    valueAdjust: 23,
    potential: 88,
    pasMax: 3
  })
  await Player.create({
    firstName: 'Daniel',
    lastName: 'Theis',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2451037.png&w=350&h=254',
    TeamUuid: celtics.dataValues.uuid,
    UserUuid: uuid,
    value: 79,
    ptsBeg: 4,
    salary: 5000000,
    contractLeft: 2,
    contractYear1: 5000000,
    contractYear2: 5000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 28,
    rebBeg: 3,
    pasBeg: 1,
    ptsMin: 4,
    ptsMax: 14,
    rebMin: 3,
    rebMax: 11,
    pasMin: 1,
    blkMin: 0.3,
    blkMax: 2.3,
    stlMin: 0,
    stlMax: 1.2,
    valueAdjust: 22.9,
    potential: 80,
    pasMax: 3
  })
  const heat = await Team.findOne({
    where: {
      name: 'Heat',
      UserUuid: uuid
    }
  })
  await Player.create({
    firstName: 'Duncan',
    lastName: 'Robinson',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3157465.png&w=350&h=254',
    TeamUuid: heat.dataValues.uuid,
    UserUuid: uuid,
    value: 78,
    ptsBeg: 6,
    salary: 1400000,
    contractLeft: 1,
    contractYear1: 1400000,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 26,
    rebBeg: 1,
    pasBeg: 0,
    ptsMin: 6,
    ptsMax: 20,
    rebMin: 1,
    rebMax: 5,
    pasMin: 0,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 41.5,
    potential: 82,
    pasMax: 2
  })
  await Player.create({
    firstName: 'Bam',
    lastName: 'Adebayo',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066261.png&w=350&h=254',
    TeamUuid: heat.dataValues.uuid,
    UserUuid: uuid,
    value: 87,
    ptsBeg: 8,
    salary: 3400000,
    contractLeft: 2,
    contractYear1: 3400000,
    contractYear2: 3400000,
    contractYear3: 0,
    contractYear4: 0,
    age: 23,
    rebBeg: 6,
    pasBeg: 2,
    ptsMin: 8,
    ptsMax: 24,
    rebMin: 6,
    rebMax: 14,
    pasMin: 2,
    blkMin: 0.3,
    blkMax: 2.3,
    stlMin: 0,
    stlMax: 2,
    valueAdjust: 0.3,
    potential: 85,
    pasMax: 8
  })
  await Player.create({
    firstName: 'Jimmy',
    lastName: 'Butler',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6430.png&w=350&h=254',
    TeamUuid: heat.dataValues.uuid,
    UserUuid: uuid,
    value: 93,
    ptsBeg: 10,
    salary: 32000000,
    contractLeft: 2,
    contractYear1: 32000000,
    contractYear2: 32000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 31,
    rebBeg: 3,
    pasBeg: 3,
    ptsMin: 10,
    ptsMax: 30,
    rebMin: 3,
    rebMax: 11,
    pasMin: 3,
    blkMin: 0,
    blkMax: 1.2,
    stlMin: 0.8,
    stlMax: 2.8,
    valueAdjust: 3.4,
    potential: 94,
    pasMax: 9
  })
  await Player.create({
    firstName: 'Goran',
    lastName: 'Dragic',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3423.png&w=350&h=254',
    TeamUuid: heat.dataValues.uuid,
    UserUuid: uuid,
    value: 81,
    ptsBeg: 6,
    salary: 19000000,
    contractLeft: 2,
    contractYear1: 19000000,
    contractYear2: 19000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 34,
    rebBeg: 1,
    pasBeg: 2,
    ptsMin: 6,
    ptsMax: 26,
    rebMin: 1,
    rebMax: 5,
    pasMin: 2,
    blkMin: 0,
    blkMax: 0.4,
    stlMin: 0,
    stlMax: 1.4,
    valueAdjust: 29.4,
    potential: 85,
    pasMax: 8
  })

  await Player.create({
    firstName: 'Andre',
    lastName: 'Iguodala',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2386.png&w=350&h=254',
    TeamUuid: heat.dataValues.uuid,
    UserUuid: uuid,
    value: 76,
    ptsBeg: 0,
    salary: 7000000,
    contractLeft: 1,
    contractYear1: 7000000,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 36,
    rebBeg: 1,
    pasBeg: 1,
    ptsMin: 0,
    ptsMax: 10,
    rebMin: 1,
    rebMax: 5,
    pasMin: 1,
    blkMin: 0,
    blkMax: 2,
    stlMin: 0,
    stlMax: 1.4,
    valueAdjust: 37.2,
    potential: 88,
    pasMax: 3
  })

  // await Player.create({
  //   firstName: 'Jae',
  //   lastName: 'Crowder',
  //   photo:
  //     'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6581.png&w=350&h=254',
  //   TeamUuid: heat.dataValues.uuid,
  //   UserUuid: uuid,
  //   value: 45.5,
  //   ptsBeg: 5,
  //   salary: 7000000,
  //   contractLeft: 2,
  //   contractYear1: 7000000,
  //   contractYear2: 7000000,
  //   contractYear3: 0,
  //   contractYear4: 0,
  //   age: 28,
  //   rebBeg: 2,
  //   pasBeg: 2,
  //   ptsMin: 5,
  //   ptsMax: 15,
  //   rebMin: 2,
  //   rebMax: 6,
  //   pasMin: 2,
  //   blkMin: 0,
  //   blkMax: 1,
  //   stlMin: 0,
  //   stlMax: 1,
  //   valueAdjust: 34.5,
  //   potential: 85,
  //   pasMax: 6
  // })

  // free agents

  await Player.create({
    firstName: 'Joe',
    lastName: 'Harris',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2528794.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 28,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  // retirements

  await Player.create({
    firstName: 'Vince',
    lastName: 'Carter',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/136.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 39,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'Udonis',
    lastName: 'Haslem',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2184.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 38,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'JaVale',
    lastName: 'McGee',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3452.png&w=350&h=254',

    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 4000000,
    contractLeft: 2,
    contractYear1: 4000000,
    contractYear2: 4000000,
    contractYear3: 0,
    contractYear4: 0,
    age: 28,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'Pau',
    lastName: 'Gasol',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/996.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 37,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'Kyle',
    lastName: 'Korver',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2011.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 36,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'Jamal',
    lastName: 'Crawford',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/165.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 36,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'J.J.',
    lastName: 'Barea',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3055.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 36,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'Marc',
    lastName: 'Gasol',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3206.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 37,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'JR',
    lastName: 'Smith',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2444.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 36,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'Kevon',
    lastName: 'Looney',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3155535.png&w=350&h=254',

    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 4000000,
    contractLeft: 1,
    contractYear1: 4000000,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 28,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })
  await Player.create({
    firstName: 'Tyson',
    lastName: 'Chandler',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/984.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 38,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  await Player.create({
    firstName: 'Danny',
    lastName: 'Green',
    photo:
      'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3988.png&w=350&h=254',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 0,
    contractLeft: 2,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 34,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6
  })

  // prospects 2020

  await Player.create({
    firstName: 'Isaac',
    lastName: 'Okoro',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200209143641-Isaac_Okoro.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 19,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 86,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Killian',
    lastName: 'Hayes',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/190622184450-Killian_Hayes.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 19,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Deni',
    lastName: 'Avdija',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200517123125-Deni_Avdija.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 19,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 82,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Lamelo',
    lastName: 'Ball',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200209143836-Tyrese_Maxey.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 19,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 87,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Anthony',
    lastName: 'Edwards',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200209015641-LaMelo_Ball.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 19,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 95,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'James',
    lastName: 'Wiseman',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200319230912-James_Wiseman.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 19,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 90,
    pasMax: 6,
    isRookie: true
  })

  // prospects 2021

  await Player.create({
    firstName: 'Cade',
    lastName: 'Cunningham',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200319212305-Cade_Cunningham.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 18,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 86,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Jonathan',
    lastName: 'Kuminga',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200823175409-Jonathan_Kuminga.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 18,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Ziaire',
    lastName: 'Williams',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200319211834-Ziaire_Williams.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 18,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 82,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Jalen',
    lastName: 'Suggs',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200423005403-Jalen_Suggs.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 18,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 87,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Jalen',
    lastName: 'Green',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200319205827-Jalen_Green.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 18,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 95,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Scottie',
    lastName: 'Barnes',
    photo:
      'https://www.envergure.co/upload/cache/player_big/upload/player/image/200423004413-Scottie_Barnes.jpeg',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 18,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 95,
    pasMax: 6,
    isRookie: true
  })

  // prospects 2022

  await Player.create({
    firstName: 'Emoni', 
    lastName: 'Bates',
    photo: 'avatar',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 17,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 86,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Victor', 
    lastName: 'Wembanyama',
    photo: 'avatar',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 17,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 85,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Chet', 
    lastName: 'Holmgren',
    photo: 'avatar',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 17,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 82,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Jaden',
    lastName: 'Hardy', 
    photo: 'avatar',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 17,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 87,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Paolo', 
    lastName: 'Banchero',
    photo: 'avatar',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 17,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 95,
    pasMax: 6,
    isRookie: true
  })
  await Player.create({
    firstName: 'Patrick', 
    lastName: 'Baldwin Jr.',
    photo: 'avatar',
    UserUuid: uuid,
    value: 45.5,
    ptsBeg: 5,
    salary: 7000000,
    contractLeft: 0,
    contractYear1: 0,
    contractYear2: 0,
    contractYear3: 0,
    contractYear4: 0,
    age: 17,
    rebBeg: 2,
    pasBeg: 2,
    ptsMin: 5,
    ptsMax: 15,
    rebMin: 2,
    rebMax: 6,
    pasMin: 2,
    blkMin: 0,
    blkMax: 1,
    stlMin: 0,
    stlMax: 1,
    valueAdjust: 34.5,
    potential: 95,
    pasMax: 6,
    isRookie: true
  })
}

module.exports = DataCreation
