GET http://localhost:8080/teams/
###
POST http://localhost:8080/teams/ HTTP/1.1
Content-Type: application/json

{
    "name" : "My team",
    "UserUuid": "e2321618-89a1-43cd-bf59-81813739d983"


}
###
POST https://mychatappmessenger.herokuapp.com/teams HTTP/1.1
Content-Type: application/json

{
    "bloodSugar" : "ok",
    "weight" : "ok",
    "mood" : "ok",
    "appetite" : "ok",
    "patientUuid": "3421d7cf-c8cd-4cde-9a33-92a0e605fc88"

}

###
DELETE https://mychatappmessenger.herokuapp.com/teams/7c5a812e-d265-409c-b922-4bf9b50fd9cc HTTP/1.1